# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca625a1417ae1e52fba512273cd36c316af4aca2e7a87ad4fa8763d565e195211a9e11ab71b56903db9f8c0cdc4ede8665a7298abfca8d81443f788bdfce9969

test:
  secret_key_base: 83140a13ff6796fbd369b119edf046b6eff1e517a5561054ae1dbdb789e8000f69895c1a7e54d1d0b455615a84cdec33256caef4602e3272ca038c79c9fa1e51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
